version: '2'
services:
  financial_api:
    build: .
    context: .
    dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: mongodb://localhost:27017/financial
  mongodb:
    image: mongo
    environment:
      MONGO_USER: admin
      MONGO_DB: financial